apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - config.yaml
  - minio.yaml
  - s3-storage.yaml
  - postgres.yaml
  - user-service.yaml
  - message-service.yaml
  - bff.yaml
  - frontend.yaml
  - migrate-users.yaml
  - migrate-messages.yaml