apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-users
spec:
  template:
    metadata:
      labels:
        app: migrate-users
    spec:
      containers:
      - name: goose
        image: ghcr.io/kukymbr/goose-docker:latest
        args: ["up"]
        env:
        - name: GOOSE_DRIVER
          value: "postgres"
        - name: GOOSE_DBSTRING
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: USER_DB_DSN
        - name: GOOSE_MIGRATION_DIR
          value: "/migrations"
      restartPolicy: OnFailure